### PR TITLE
Fully automate dev setup with Gitpod

### PR DESCRIPTION
**Pull request by DoPaNik**
This commit implements a fully-automated development setup using Gitpod.io, an
online IDE for GitHub and GitLab that enables Dev-Environments-As-Code.
This makes it easy for anyone to get a ready-to-code workspace for any branch,
issue or pull request almost instantly with a single click.

Add useful extensions to project

### CODE REVIEW

**Comment by simonech** [comment]
Why not github codespaces?

**Comment by DoPaNik** [comment]
I am currently on the waiting list :P

**Comment by simonech** [comment]
> I am currently on the waiting list :P

I'm not 😄

**Comment by DoPaNik** [comment]
> > I am currently on the waiting list :P
> 
> I'm not 😄

supporting both cannot hurt either! ;-)

**Comment by jimmykane** [comment]
What do you think about supporting both and merging this ?

**Comment by jimmykane** [comment]
And hey @simonech  nice to see you here 🙏🙏🙏

**Comment by simonech** [comment]
I’m playing with codespaces for work.
I’ll give it a go. But for keeping it clearer, probably better as 2 separate PRs.

**Comment by DoPaNik** [comment]
I think for now, gitpod is the broader platform that makes it much easier for new people to support the project. Since Github's codespaces is still being tested and only available to a few, I think I would prefer gitpod.

**Pull request merged**
