### PR TITLE
#212 - Add Github actions to deploy to firebase

### PR DESCRIPTION
**Pull request by DoPaNik**
I haven't yet got around to setting up firebase correctly with everything (functions and co). Actually a rudimentary deployment should work so far. But I will continue to work on it - but maybe early feedback would be valuable.

### CODE REVIEW

**Comment by jimmykane** [comment]
@DoPaNik Hey thanks. Lets not worry so much about the functions. Lets get the hosting deployed. 

On travis one thing I had was only when a tag was pushed would deploy. Not essential but in this way you would bump the version, tag and deploy. 

What do you think about this?

**Comment by DoPaNik** [comment]
@jimmykane Unfortunately the functions block the deploy process for me. That's why i couldn't really test the hosting.

I like the idea with the tags! I will integrate this also in this action later :-)

**Comment by jimmykane** [comment]
@DoPaNik How do the functions deployment fail? (I haven't tested the pr yet). 

We could also , seperate the project (but that might be too much)

**Comment by DoPaNik** [comment]
@jimmykane no, I think so is the project structure okay. But I have not yet configured firebase in a way that everything works and I have not yet understood everything completely. I am on it ;)

**Comment by DoPaNik** [comment]
@jimmykane now it can be deployed to firebase via github actions. The action is only started if a 'sem tag` is assigned. e.g. v6.8.5

**Comment by jimmykane** [comment]
Looks good. But 1 question. Do you prefer the v1.0.0 or 1.0.0 version formating. 

Up to this point I have ommited the `v` just because I find it redundant, but I had used it in the past on some tags accidnetaly. 

Should I modify the PR to use non-`v` tags?

**Comment by jimmykane** [comment]
I could also change how the tags are named on the repo.....

**Comment by DoPaNik** [comment]
> Looks good. But 1 question. Do you prefer the v1.0.0 or 1.0.0 version formating.
> 
> Up to this point I have ommited the `v` just because I find it redundant, but I had used it in the past on some tags accidnetaly.
> 
> Should I modify the PR to use non-`v` tags?

Of course you're right, especially with the tags it's kind of redundant, but if the version appears alone somewhere else, then it's obvious that it's a version number. That's why I would rather tend to include the V in the naming.

**Comment by jimmykane** [comment]
Hey I merged this and will test on next release 

btw have you checked this: https://github.com/marketplace/actions/github-action-for-firebase ?

**Comment by jimmykane** [comment]
Oh and this https://github.com/marketplace/actions/deploy-to-firebase-hosting :-D

**Comment by DoPaNik** [comment]
Oh I only tried this one -> https://github.com/jimmykane/quantified-self/pull/216/commits/830433880f9d415b0e12e5ac0ab601170e3d430c I just didn't understand why i should use such a plugin, which needs loading time, if I don't need the overhead at all - and in case of my choosen plugin I can't even add parameters 🤣

**Comment by jimmykane** [comment]
Alright no worries I was just speaking out loud. I ll give this a try asap but first I have to fix a queue issue :-/

**Pull request merged**
