### PR TITLE
Support 'Speed' as datatype in charts

### PR DESCRIPTION
**Pull request by sehaas**
- add avg/min/max speed
- respect user unit settings

### CODE REVIEW

**Comment by sehaas** [comment]
@jimmykane how can I trigger the `run_tests` task for this PR? This check is still in `Expected - Waiting...`
Screenshot_20201027-162112

Thanks,
  Sebastian

**Comment by jimmykane** [comment]
Hey. I somehow just saw this. Let me get back in the weekend about this. 

Till then thank you very much and may you have a great rest of the day @sehaas

**Comment by jimmykane** [comment]
Hey I have not forgotten you

**Review by jimmykane — APPROVED** [review]
Thanks for this. Very elegant solution to the Unit based problem I have not correctly solved

**Pull request merged**
